# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpochHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('hashes', models.TextField()),
                ('signature', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EpochSummary',
            fields=[
                ('epoch', models.IntegerField(primary_key=True, serialize=False)),
                ('epoch_seed', models.CharField(max_length=64)),
                ('transaction_count', models.IntegerField(default=0)),
                ('count_duration', models.DurationField()),
                ('apply_duration', models.DurationField()),
                ('seed_duration', models.DurationField()),
            ],
            options={
                'get_latest_by': 'epoch',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('address', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'last_updated',
            },
        ),
        migrations.CreateModel(
            name='NodePenaltyVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_for', models.BooleanField(default=False)),
                ('epoch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EpochSummary')),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('domain', models.TextField(primary_key=True, serialize=False)),
                ('reputation', models.FloatField(default=0)),
                ('first_registered', models.DateTimeField()),
                ('payout_address', models.TextField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedRejection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Peer')),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedTransaction',
            fields=[
                ('txid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('applied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='validatedrejection',
            name='tx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ValidatedTransaction'),
        ),
        migrations.AddField(
            model_name='validatedmovement',
            name='tx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ValidatedTransaction'),
        ),
        migrations.AddField(
            model_name='nodepenaltyvote',
            name='penalized_peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalization_subject', to='main.Peer'),
        ),
        migrations.AddField(
            model_name='nodepenaltyvote',
            name='voting_peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalization_vote', to='main.Peer'),
        ),
        migrations.AddField(
            model_name='epochhash',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Peer'),
        ),
    ]
