# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('address', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'last_updated',
            },
        ),
        migrations.CreateModel(
            name='LedgerHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64)),
                ('epoch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('domain', models.TextField(primary_key=True, serialize=False)),
                ('reputation', models.FloatField(default=0)),
                ('first_registered', models.DateTimeField()),
                ('payout_address', models.TextField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedTransaction',
            fields=[
                ('txid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('rejected_reputation_percentile', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='validatedmovement',
            name='tx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ValidatedTransaction'),
        ),
    ]
