# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EpochTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch_number', models.IntegerField()),
                ('transactions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('address', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'last_updated',
            },
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('domain', models.TextField(primary_key=True, serialize=False)),
                ('reputation', models.FloatField(default=0)),
                ('first_registered', models.DateTimeField()),
                ('payout_address', models.TextField(max_length=40, unique=True)),
            ],
        ),
    ]
